In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import time
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('/content/data.csv - Sheet1.csv')

In [3]:
df.head()

  timestamp,open,high,low,close,volume_btc,volume_usd
0  2024-01-01 00:00:00,44910.83,45085.78,44910.83...
1  2024-01-01 00:01:00,44977.19,45045.33,44977.19...
2  2024-01-01 00:02:00,44991.38,45103.85,44965.65...
3  2024-01-01 00:03:00,45056.78,45135.78,45056.78...
4  2024-01-01 00:04:00,45172.02,45222.19,44979.72...

In [4]:
df.columns

Index(['timestamp,open,high,low,close,volume_btc,volume_usd'], dtype='object')

In [5]:
df.isnull().sum()

timestamp,open,high,low,close,volume_btc,volume_usd    0
dtype: int64

In [6]:
df.describe

<bound method NDFrame.describe of      timestamp,open,high,low,close,volume_btc,volume_usd
0     2024-01-01 00:00:00,44910.83,45085.78,44910.83...
1     2024-01-01 00:01:00,44977.19,45045.33,44977.19...
2     2024-01-01 00:02:00,44991.38,45103.85,44965.65...
3     2024-01-01 00:03:00,45056.78,45135.78,45056.78...
4     2024-01-01 00:04:00,45172.02,45222.19,44979.72...
...                                                 ...
9995  2024-01-07 22:35:00,44139.5,44187.67,44102.45,...
9996  2024-01-07 22:36:00,44165.1,44177.54,43928.89,...
9997  2024-01-07 22:37:00,44083.32,44083.32,43977.78...
9998  2024-01-07 22:38:00,44057.8,44196.97,43879.32,...
9999  2024-01-07 22:39:00,44061.71,44220.17,44057.19...

[10000 rows x 1 columns]>

In [7]:
df.info

<bound method DataFrame.info of      timestamp,open,high,low,close,volume_btc,volume_usd
0     2024-01-01 00:00:00,44910.83,45085.78,44910.83...
1     2024-01-01 00:01:00,44977.19,45045.33,44977.19...
2     2024-01-01 00:02:00,44991.38,45103.85,44965.65...
3     2024-01-01 00:03:00,45056.78,45135.78,45056.78...
4     2024-01-01 00:04:00,45172.02,45222.19,44979.72...
...                                                 ...
9995  2024-01-07 22:35:00,44139.5,44187.67,44102.45,...
9996  2024-01-07 22:36:00,44165.1,44177.54,43928.89,...
9997  2024-01-07 22:37:00,44083.32,44083.32,43977.78...
9998  2024-01-07 22:38:00,44057.8,44196.97,43879.32,...
9999  2024-01-07 22:39:00,44061.71,44220.17,44057.19...

[10000 rows x 1 columns]>

In [8]:
df.dtypes

timestamp,open,high,low,close,volume_btc,volume_usd    object
dtype: object

In [9]:
df = df.iloc[:, 0].str.split(",", expand=True)
df.columns = [
    "timestamp",
    "open",
    "high",
    "low",
    "close",
    "volume_btc",
    "volume_usd",
]

In [10]:
df.head()

,timestamp,open,high,low,close,volume_btc,volume_usd
0,2024-01-01 00:00:00,44910.83,45085.78,44910.83,45024.68,3.640837,163927.55
1,2024-01-01 00:01:00,44977.19,45045.33,44977.19,45017.83,33.752474,1519463.07
2,2024-01-01 00:02:00,44991.38,45103.85,44965.65,45050.03,5.488855,247273.08
3,2024-01-01 00:03:00,45056.78,45135.78,45056.78,45125.82,8.464271,381957.14
4,2024-01-01 00:04:00,45172.02,45222.19,44979.72,45114.17,21.673405,977777.67

In [11]:
df.head()

,timestamp,open,high,low,close,volume_btc,volume_usd
0,2024-01-01 00:00:00,44910.83,45085.78,44910.83,45024.68,3.640837,163927.55
1,2024-01-01 00:01:00,44977.19,45045.33,44977.19,45017.83,33.752474,1519463.07
2,2024-01-01 00:02:00,44991.38,45103.85,44965.65,45050.03,5.488855,247273.08
3,2024-01-01 00:03:00,45056.78,45135.78,45056.78,45125.82,8.464271,381957.14
4,2024-01-01 00:04:00,45172.02,45222.19,44979.72,45114.17,21.673405,977777.67

In [12]:
df.isnull().sum()

timestamp     0
open          0
high          0
low           0
close         0
volume_btc    0
volume_usd    0
dtype: int64

In [13]:
df

,timestamp,open,high,low,close,volume_btc,volume_usd
0,2024-01-01 00:00:00,44910.83,45085.78,44910.83,45024.68,3.640837,163927.55
1,2024-01-01 00:01:00,44977.19,45045.33,44977.19,45017.83,33.752474,1519463.07
2,2024-01-01 00:02:00,44991.38,45103.85,44965.65,45050.03,5.488855,247273.08
3,2024-01-01 00:03:00,45056.78,45135.78,45056.78,45125.82,8.464271,381957.14
4,2024-01-01 00:04:00,45172.02,45222.19,44979.72,45114.17,21.673405,977777.67
...,...,...,...,...,...,...,...
9995,2024-01-07 22:35:00,44139.5,44187.67,44102.45,44153.42,8.046188,355266.76
9996,2024-01-07 22:36:00,44165.1,44177.54,43928.89,44056.18,7.117921,313588.41
9997,2024-01-07 22:37:00,44083.32,44083.32,43977.78,44021.92,15.644622,688706.27
9998,2024-01-07 22:38:00,44057.8,44196.97,43879.32,44046.02,10.999206,484471.26
9999,2024-01-07 22:39:00,44061.71,44220.17,44057.19,44077.36,71.787946,3164223.36

In [14]:
df["timestamp"] = pd.to_datetime(df["timestamp"])

In [15]:
df

,timestamp,open,high,low,close,volume_btc,volume_usd
0,2024-01-01 00:00:00,44910.83,45085.78,44910.83,45024.68,3.640837,163927.55
1,2024-01-01 00:01:00,44977.19,45045.33,44977.19,45017.83,33.752474,1519463.07
2,2024-01-01 00:02:00,44991.38,45103.85,44965.65,45050.03,5.488855,247273.08
3,2024-01-01 00:03:00,45056.78,45135.78,45056.78,45125.82,8.464271,381957.14
4,2024-01-01 00:04:00,45172.02,45222.19,44979.72,45114.17,21.673405,977777.67
...,...,...,...,...,...,...,...
9995,2024-01-07 22:35:00,44139.5,44187.67,44102.45,44153.42,8.046188,355266.76
9996,2024-01-07 22:36:00,44165.1,44177.54,43928.89,44056.18,7.117921,313588.41
9997,2024-01-07 22:37:00,44083.32,44083.32,43977.78,44021.92,15.644622,688706.27
9998,2024-01-07 22:38:00,44057.8,44196.97,43879.32,44046.02,10.999206,484471.26
9999,2024-01-07 22:39:00,44061.71,44220.17,44057.19,44077.36,71.787946,3164223.36

In [16]:
cols = [
    "open",
    "high",
    "low",
    "close",
    "volume_btc",
    "volume_usd"
]

df[cols] = df[cols].astype(float)

In [17]:
df.dtypes

timestamp     datetime64[ns]
open                 float64
high                 float64
low                  float64
close                float64
volume_btc           float64
volume_usd           float64
dtype: object

In [18]:
df['rolling_mean'] = df['close'].rolling(window=5).mean()

In [19]:
df['signal'] = (df['close'] > df['rolling_mean']).astype(float)

In [20]:
rows_processed = len(df)
signal_rate = df['signal'].mean()

In [21]:
start = time.perf_counter()

In [22]:
df.dtypes

timestamp       datetime64[ns]
open                   float64
high                   float64
low                    float64
close                  float64
volume_btc             float64
volume_usd             float64
rolling_mean           float64
signal                 float64
dtype: object

In [23]:
df.empty

False

In [24]:
df.isnull().sum()

timestamp       0
open            0
high            0
low             0
close           0
volume_btc      0
volume_usd      0
rolling_mean    4
signal          0
dtype: int64

In [25]:
"close" in df.columns

True

In [26]:
df.head()

,timestamp,open,high,low,close,volume_btc,volume_usd,rolling_mean,signal
0,2024-01-01 00:00:00,44910.83,45085.78,44910.83,45024.68,3.640837,163927.55,NaN,0.0
1,2024-01-01 00:01:00,44977.19,45045.33,44977.19,45017.83,33.752474,1519463.07,NaN,0.0
2,2024-01-01 00:02:00,44991.38,45103.85,44965.65,45050.03,5.488855,247273.08,NaN,0.0
3,2024-01-01 00:03:00,45056.78,45135.78,45056.78,45125.82,8.464271,381957.14,NaN,0.0
4,2024-01-01 00:04:00,45172.02,45222.19,44979.72,45114.17,21.673405,977777.67,45066.506,1.0

In [27]:
df["rolling_mean"] = df["close"].rolling(window=5).mean()

In [28]:
df[['close','rolling_mean']].head(1)

      close  rolling_mean
0  45024.68           NaN

In [29]:
df['signal'] = df['signal'].astype(int)

In [30]:
df

,timestamp,open,high,low,close,volume_btc,volume_usd,rolling_mean,signal
0,2024-01-01 00:00:00,44910.83,45085.78,44910.83,45024.68,3.640837,163927.55,NaN,0
1,2024-01-01 00:01:00,44977.19,45045.33,44977.19,45017.83,33.752474,1519463.07,NaN,0
2,2024-01-01 00:02:00,44991.38,45103.85,44965.65,45050.03,5.488855,247273.08,NaN,0
3,2024-01-01 00:03:00,45056.78,45135.78,45056.78,45125.82,8.464271,381957.14,NaN,0
4,2024-01-01 00:04:00,45172.02,45222.19,44979.72,45114.17,21.673405,977777.67,45066.506,1
...,...,...,...,...,...,...,...,...,...
9995,2024-01-07 22:35:00,44139.50,44187.67,44102.45,44153.42,8.046188,355266.76,44090.590,1
9996,2024-01-07 22:36:00,44165.10,44177.54,43928.89,44056.18,7.117921,313588.41,44087.300,0
9997,2024-01-07 22:37:00,44083.32,44083.32,43977.78,44021.92,15.644622,688706.27,44070.714,0
9998,2024-01-07 22:38:00,44057.80,44196.97,43879.32,44046.02,10.999206,484471.26,44073.520,0
9999,2024-01-07 22:39:00,44061.71,44220.17,44057.19,44077.36,71.787946,3164223.36,44070.980,1

In [31]:
latency_ms = (time.perf_counter() - start) * 1000

In [32]:
latency_ms

134.86761300009675

In [33]:
df.to_csv("data.csv", index=False)